version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Listing files in $(pwd)"
      - ls -alh
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo "Build started on `date`"
      - npm run build
      - echo "After build, listing files in $(pwd)"
      - ls -alh
      - echo "Zipping build directory into build.zip"
      - zip -r build.zip build/ # This command assumes 'build' is the directory where your files are

artifacts:
  files:
    - build.zip  # This should match the name of the zip file created