version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Listing files in $(pwd)"
      - ls -alh
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo "Build started on `date`"
      - npm run build
      - echo "After build, listing files in $(pwd)"
      - ls -alh
  post_build:
    commands:
      - echo "Post build, listing files in build directory"
      - ls -alh build/
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'  # This includes all files and subdirectories
    - 'package.json' # Include the package.json file from the root
    - 'server.js' # Include the server.js if it's in the root
    - '.ebextensions/**/*' # If you're using Elastic Beanstalk extensions
    - '.platform/**/*' # If you're using platform hooks
    - 'Procfile' # Include the Procfile if you have one
  discard-paths: no # This will keep the directory structure intact
  base-directory: '/'  # Ensure this points to the root directory containing all necessary files
