version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Listing files in $(pwd)"
      - ls -alh
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo "Build started on `date`"
      - npm run build
      - echo "After build, listing files in $(pwd)"
      - ls -alh
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
